import { useState, useEffect } from 'react';
import { useApp } from '@/context/AppContext';
import { InfiniteCanvas, type CanvasContribution } from '@/components/InfiniteCanvas';
import { AICopilotPanel } from '@/components/AICopilotPanel';
import { LayerSwitcher } from '@/components/LayerSwitcher';
import { ChaosCoinsDisplay } from '@/components/ChaosCoinsDisplay';
import { ContributionFeed } from '@/components/ContributionFeed';
import { MemeEconomyDashboard } from '@/components/MemeEconomyDashboard';
import { PersonalBubblePanel } from '@/components/PersonalBubblePanel';
import { ExportPanel } from '@/components/ExportPanel';
import { LanguageCurrencySelector } from '@/components/LanguageCurrencySelector';
import { ThemeToggle } from '@/components/ThemeToggle';
import type { LayerType } from '@shared/schema';

interface Layer {
  id: string;
  type: LayerType;
  name: string;
  regionCode: string;
}

export default function CanvasPage() {
  const { t, chaosCoins } = useApp();
  const [isCopilotCollapsed, setIsCopilotCollapsed] = useState(false);
  const [currentLayer, setCurrentLayer] = useState<Layer>({
    id: 'global-1',
    type: 'global',
    name: 'Global Canvas',
    regionCode: 'global',
  });

  const [breadcrumbs, setBreadcrumbs] = useState<Layer[]>([currentLayer]);
  const [contributions, setContributions] = useState<CanvasContribution[]>([]);
  const [contributionFeed, setContributionFeed] = useState<any[]>([]);
  const [memeStocks, setMemeStocks] = useState<any[]>([]);
  const [userPortfolio, setUserPortfolio] = useState<any[]>([]);

  // Mock data for MVP demonstration
  useEffect(() => {
    // Mock contributions on canvas
    setContributions([
      {
        id: 'c1',
        userId: 'user1',
        contentType: 'text',
        contentData: { text: 'Welcome to ChaosCanvas!' },
        positionX: 100,
        positionY: 100,
        width: 200,
        height: 100,
        boostCount: 5,
      },
      {
        id: 'c2',
        userId: 'user2',
        contentType: 'text',
        contentData: { text: 'Double-click to add content', prompt: 'Generated by AI' },
        positionX: 400,
        positionY: 200,
        width: 250,
        height: 120,
        boostCount: 12,
      },
    ]);

    // Mock contribution feed
    setContributionFeed([
      {
        id: 'f1',
        userId: 'user1',
        username: 'ChaosCreator',
        contentType: 'text',
        contentData: { text: 'My first contribution!', prompt: 'Epic chaos' },
        positionX: 0,
        positionY: 0,
        width: 200,
        height: 100,
        boostCount: 5,
        viewCount: 42,
        marketPrice: '15.50',
        createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(), // 5 min ago
      },
      {
        id: 'f2',
        userId: 'user2',
        username: 'ArtMaster',
        contentType: 'image',
        contentData: { prompt: 'Cyberpunk city', style: 'pixel' },
        positionX: 0,
        positionY: 0,
        width: 300,
        height: 200,
        boostCount: 23,
        viewCount: 156,
        marketPrice: '28.75',
        createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(), // 15 min ago
      },
    ]);

    // Mock meme stocks
    setMemeStocks([
      {
        contributionId: 's1',
        title: 'Epic Dragon Meme',
        currentPrice: 25,
        priceChange: 15.3,
        boostCount: 45,
      },
      {
        contributionId: 's2',
        title: 'Confused Cat',
        currentPrice: 18,
        priceChange: -5.2,
        boostCount: 32,
      },
    ]);
  }, []);

  const handleLayerChange = (layer: Layer) => {
    setCurrentLayer(layer);
    // Update breadcrumbs based on layer hierarchy
    const index = breadcrumbs.findIndex(b => b.id === layer.id);
    if (index >= 0) {
      setBreadcrumbs(breadcrumbs.slice(0, index + 1));
    }
  };

  const handleAddContribution = async (x: number, y: number) => {
    console.log('Add contribution at', x, y);
    // Will be implemented with AI generation in backend integration
  };

  const handleGenerateContent = async (prompt: string, style: string) => {
    console.log('Generate content:', prompt, style);
    // Will be implemented with OpenAI integration
  };

  const handleBoost = (contributionId: string) => {
    console.log('Boost contribution:', contributionId);
    // Will be implemented with backend integration
  };

  const handleInvest = (contributionId: string, amount: number) => {
    console.log('Invest:', contributionId, amount);
    // Will be implemented with meme economy backend
  };

  return (
    <div className="flex h-screen w-full overflow-hidden">
      {/* AI Co-Pilot Panel (Left) */}
      <AICopilotPanel
        isCollapsed={isCopilotCollapsed}
        onToggleCollapse={() => setIsCopilotCollapsed(!isCopilotCollapsed)}
        onGenerateContent={handleGenerateContent}
      />

      {/* Main Canvas Area */}
      <div className="flex-1 flex flex-col overflow-hidden">
        {/* Top Bar */}
        <div className="flex items-center justify-between px-4 py-3 border-b border-border bg-card/50 backdrop-blur-sm">
          <div className="flex items-center gap-4">
            <h1 className="font-heading font-bold text-xl text-primary">{t('appName')}</h1>
            <p className="text-sm text-muted-foreground hidden md:block">{t('tagline')}</p>
          </div>

          <div className="flex items-center gap-2">
            <ExportPanel />
            <PersonalBubblePanel />
            <MemeEconomyDashboard
              stocks={memeStocks}
              userPortfolio={userPortfolio}
              onInvest={handleInvest}
            />
            <ChaosCoinsDisplay
              balance={chaosCoins}
              subscriptionTier={null}
            />
            <LanguageCurrencySelector />
            <ThemeToggle />
          </div>
        </div>

        {/* Layer Switcher */}
        <LayerSwitcher
          currentLayer={currentLayer}
          breadcrumbs={breadcrumbs}
          onLayerChange={handleLayerChange}
        />

        {/* Infinite Canvas */}
        <div className="flex-1 overflow-hidden">
          <InfiniteCanvas
            layerId={currentLayer.id}
            contributions={contributions}
            onAddContribution={handleAddContribution}
          />
        </div>
      </div>

      {/* Contribution Feed (Right) */}
      <div className="w-80 hidden lg:block">
        <ContributionFeed
          contributions={contributionFeed}
          onBoost={handleBoost}
        />
      </div>
    </div>
  );
}
